spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wtet
    username: root
    password: root

  jpa:
#    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace
file:
  dir: C:/WTET/store/
  defaultDir: C:/WTET/

